image: docker:19.03.1

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.1-dind

before_script:
  - docker info
build:
    stage: build
    script:
        - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
        - pip install docker-compose
        - docker-compose build
        - docker-compose up -d
test:
    stage: test
    script:
      - apk add --update nodejs npm
      - apk add --update npm
      - cd Server
      - npm i -g mocha
      - mocha __tests__/*

