version: "3.7"
services:
  server:
    container_name: server
    restart: always
    build: server/.
    ports:
      - "4000:4000"
    links:
      - mongo
  client:
    hostname: localhost
    container_name: client
    restart: always
    build: client/.
    ports:
      - "80:80"
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"