version: "3.7"
services:
  server:
    container_name: server
    restart: always
    build: Server/.
    ports:
      - "4000:4000"
    links:
      - mongo
    networks:
      - the_net
  client:
    container_name: client
    restart: always
    build: Client/.
    ports:
      - "4200:4200"
    links: 
      - server
    networks:
      - the_net
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - the_net
  
networks:
  the_net: